### ISSUE TITLE
Allow Twitter Card Update

### ISSUE THREAD

**Issue by discoverlance-com** [Honeystone/laravel-seo#1]
Hello, I want to suggest an update to the twitter generator to support updating the twitter card, `<meta name="twitter:card" content="summary_large_image">`.

Currently, it only supports the `summary_large_image`. There are other cards like `summary` that I wanted to use and I realized that when I update the config with `'card' => 'summary'`, it does not work. 

It will be great if this is supported. I know twitter cards like [player card](https://developer.x.com/en/docs/x-for-websites/cards/overview/player-card) and [app card](https://developer.x.com/en/docs/x-for-websites/cards/overview/app-card) could be a bit complex with more data required so at least changing the card to [summary card](https://developer.x.com/en/docs/x-for-websites/cards/overview/summary) should be possible.

**Comment by PiranhaGeorge** [comment]
I've just tagged version 1.4.0 which has support for all Twitter cards and the additional/missing properties. If you could give it a go and let me know how you get on, that would be great.

Cheers!

**Comment by discoverlance-com** [comment]
Hello, @PiranhaGeorge , I tested it out and I am able to update the card. Thanks very much for this update.
